services:
  web:
    env_file:
      - .env
    container_name: flask_user_management
    build:
      context: .
      dockerfile: DockerfileProd
    command: >
        sh -c "
              alembic upgrade head && 
              gunicorn -b 0.0.0.0:5000 src.main:app"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: 'always'

  nginx:
    image: nginx:1.27.4-alpine3.21
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: 'always'

  db:
    image: postgres:16.4-alpine
    container_name: postgres_user_management
    volumes:
      - postgres_user_management_volume:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=${SUPER_USER_PWD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}

    restart: 'always'

volumes:
  postgres_user_management_volume:
